Repository spacious-team/investbook, pull requests merged in 2020-09, with the labels that each got.

#92 Корректировать невалидные символы в имени листа Excel
  pom.xml
  src/main/java/ru/investbook/view/excel/ExcelTableView.java
  src/main/java/ru/investbook/view/excel/PortfolioStatusExcelTableView.java
  src/main/java/ru/investbook/view/excel/StockMarketProfitExcelTableView.java
Labels: bug, critical

#93 Добавить таблицу Комиссия
  README.md
  src/main/asciidoc/commission.adoc
  src/main/asciidoc/index.adoc
  src/main/java/ru/investbook/view/excel/CommissionExcelTableFactory.java
  src/main/java/ru/investbook/view/excel/CommissionExcelTableHeader.java
  src/main/java/ru/investbook/view/excel/CommissionExcelTableView.java
  src/main/java/ru/investbook/view/excel/ExcelView.java
Labels: feature, minor

#95 Поправить опечатки в portfolio-status.adoc
  src/main/asciidoc/portfolio-status.adoc
Labels: doc, major

#96 Исправление опечатов в документации.adoc
  src/main/asciidoc/portfolio-status.adoc
Labels: doc, major

#105 Выбор режима выгрузки: на заданную дату или за период
  src/main/resources/templates/index.html
Labels: improvement, minor

#106 Уралсиб брокер. Учитывать дублирующую выплату, полученную по связанному счету
  src/main/asciidoc/portfolio-status.adoc
  src/main/java/ru/investbook/parser/table/AbstractTable.java
  src/main/java/ru/investbook/parser/table/Table.java
  src/main/java/ru/investbook/parser/uralsib/CouponAmortizationRedemptionTable.java
  src/main/java/ru/investbook/parser/uralsib/DividendTable.java
  src/main/java/ru/investbook/parser/uralsib/PaymentsTable.java
Labels: bug, critical
