Repository spacious-team/investbook, pull requests merged in 2020-05, with the labels that each got.

#41 Add log to gitignore
  .gitignore
Labels: minor, task

#39 Issue #36 Add link to main page
  src/main/java/ru/portfolio/portfolio/parser/ReportRestController.java
Labels: improvement, minor

#42 Фильтрация результатов
  src/main/java/ru/portfolio/portfolio/view/excel/CashFlowExcelTableView.java
  src/main/java/ru/portfolio/portfolio/view/excel/DerivativesMarketProfitExcelTableView.java
  src/main/java/ru/portfolio/portfolio/view/excel/ExcelTableView.java
Labels: improvement, minor

#40 Fix typos
  README.md
  src/main/java/ru/portfolio/portfolio/controller/AbstractRestController.java
  src/main/java/ru/portfolio/portfolio/parser/BrokerType.java
  src/main/java/ru/portfolio/portfolio/parser/ExcelTable.java
  src/main/java/ru/portfolio/portfolio/parser/ExcelTableHelper.java
  src/main/java/ru/portfolio/portfolio/parser/MultiLineTableColumn.java
  src/main/java/ru/portfolio/portfolio/parser/RelativePositionTableColumn.java
  src/main/java/ru/portfolio/portfolio/parser/ReportRestController.java
  src/main/java/ru/portfolio/portfolio/parser/psb/DerivativeCashFlowTable.java
  src/main/java/ru/portfolio/portfolio/parser/psb/PsbBrokerReport.java
  src/main/java/ru/portfolio/portfolio/parser/uralsib/DividendTable.java
  src/main/java/ru/portfolio/portfolio/parser/uralsib/PaymentsTable.java
  src/main/java/ru/portfolio/portfolio/parser/uralsib/PortfolioPropertyTable.java
  src/main/java/ru/portfolio/portfolio/parser/uralsib/PortfolioSecuritiesTable.java
  src/main/java/ru/portfolio/portfolio/parser/uralsib/SecurityTransactionTable.java
  src/main/java/ru/portfolio/portfolio/parser/uralsib/UralsibBrokerReport.java
  src/main/java/ru/portfolio/portfolio/view/PortfolioViewRestController.java
  src/main/java/ru/portfolio/portfolio/view/excel/CellStyles.java
  src/main/java/ru/portfolio/portfolio/view/excel/StockMarketProfitExcelTableFactory.java
Labels: minor, task

#43 Фикс ошибки вывода транзакции в день с нулевой вариационной маржой
  src/main/java/ru/portfolio/portfolio/view/DerivativeCashFlowFactory.java
  src/main/java/ru/portfolio/portfolio/view/DerivativeEvents.java
  src/main/java/ru/portfolio/portfolio/view/DerivativeEventsFactory.java
  src/main/java/ru/portfolio/portfolio/view/excel/DerivativesMarketProfitExcelTableFactory.java
Labels: bug, major

#45 Вынести сделки на валютной секции в отдельную таблицу
  src/main/java/ru/portfolio/portfolio/view/PaidInterest.java
  src/main/java/ru/portfolio/portfolio/view/excel/ExcelView.java
  src/main/java/ru/portfolio/portfolio/view/excel/ForeignMarketProfitExcelTableFactory.java
  src/main/java/ru/portfolio/portfolio/view/excel/ForeignMarketProfitExcelTableHeader.java
  src/main/java/ru/portfolio/portfolio/view/excel/ForeignMarketProfitExcelTableView.java
  src/main/java/ru/portfolio/portfolio/view/excel/StockMarketProfitExcelTableFactory.java
Labels: improvement, major
