Repository spacious-team/investbook, pull requests merged in 2021-08, with the labels that each got.

#346 Добавлена колонка enabled в таблицу portfolio
  src/main/resources/db/migration/all/V2021_8_0_0.sql
Labels: feature, minor

#348 Формы. Добавлены события Возврата налога и комиссии
  src/main/java/ru/investbook/web/forms/model/EventCashFlowModel.java
  src/main/java/ru/investbook/web/forms/service/EventCashFlowFormsService.java
  src/main/resources/templates/events/edit-form.html
  src/main/resources/templates/events/table.html
  src/main/resources/templates/events/view-single.html
Labels: bug, major

#349 СУБД разработчика изменена на H2
  src/main/resources/application-dev.properties
Labels: minor, task

#350 Добавлено поле enabled в PortfolioEntity и обработка этого поля в PortfolioConverter
  pom.xml
  src/main/java/ru/investbook/converter/PortfolioConverter.java
  src/main/java/ru/investbook/entity/PortfolioEntity.java
Labels: feature, minor
