Repository spacious-team/investbook, pull requests merged in 2021-12, with the labels that each got.

#377 Поддержка произвольных активов
  pom.xml
  src/main/java/ru/investbook/report/FifoPositionsFactory.java
  src/main/java/ru/investbook/report/ForeignExchangeRateService.java
  src/main/java/ru/investbook/report/excel/PortfolioStatusExcelTableFactory.java
  src/main/java/ru/investbook/repository/SecurityRepository.java
  src/main/java/ru/investbook/repository/TransactionRepository.java
  src/main/java/ru/investbook/service/SecurityProfitServiceImpl.java
  src/main/java/ru/investbook/service/SecuritySectorService.java
  src/main/java/ru/investbook/service/moex/MoexIssClientImpl.java
  src/main/java/ru/investbook/service/moex/MoexJsonResponseParser.java
  src/main/java/ru/investbook/web/ControllerHelper.java
  src/main/java/ru/investbook/web/forms/model/SecurityDescriptionModel.java
  src/main/java/ru/investbook/web/forms/model/SecurityEventCashFlowModel.java
  src/main/java/ru/investbook/web/forms/model/SecurityHelper.java
  src/main/java/ru/investbook/web/forms/model/SecurityQuoteModel.java
  src/main/java/ru/investbook/web/forms/model/SecurityType.java
  src/main/java/ru/investbook/web/forms/model/TransactionModel.java
  src/main/java/ru/investbook/web/forms/service/SecurityDescriptionFormsService.java
  src/main/java/ru/investbook/web/forms/service/SecurityEventCashFlowFormsService.java
  src/main/java/ru/investbook/web/forms/service/SecurityQuoteFormsService.java
  src/main/java/ru/investbook/web/forms/service/SecurityRepositoryHelper.java
  src/main/java/ru/investbook/web/forms/service/TransactionFormsService.java
  src/main/resources/templates/security-descriptions/edit-form.html
  src/main/resources/templates/security-descriptions/table.html
  src/main/resources/templates/security-descriptions/view-single.html
  src/main/resources/templates/security-quotes/edit-form.html
  src/main/resources/templates/security-quotes/table.html
  src/main/resources/templates/transactions/edit-form.html
Labels: feature, major

#379 Релиз 2021.10
  README.md
  docs/install-on-linux.md
  docs/install-on-windows-by-zip.md
  docs/install-on-windows.md
  pom.xml
  src/main/asciidoc/troubleshooting.adoc
  src/main/java/ru/investbook/report/FifoPositionsFactory.java
  src/main/java/ru/investbook/report/ForeignExchangeRateService.java
  src/main/java/ru/investbook/report/excel/PortfolioStatusExcelTableFactory.java
  src/main/java/ru/investbook/repository/SecurityRepository.java
  src/main/java/ru/investbook/repository/TransactionRepository.java
  src/main/java/ru/investbook/service/SecurityProfitServiceImpl.java
  src/main/java/ru/investbook/service/SecuritySectorService.java
  src/main/java/ru/investbook/service/moex/MoexIssClientImpl.java
  src/main/java/ru/investbook/service/moex/MoexJsonResponseParser.java
  src/main/java/ru/investbook/web/ControllerHelper.java
  src/main/java/ru/investbook/web/forms/model/SecurityDescriptionModel.java
  src/main/java/ru/investbook/web/forms/model/SecurityEventCashFlowModel.java
  src/main/java/ru/investbook/web/forms/model/SecurityHelper.java
  src/main/java/ru/investbook/web/forms/model/SecurityQuoteModel.java
  src/main/java/ru/investbook/web/forms/model/SecurityType.java
  src/main/java/ru/investbook/web/forms/model/TransactionModel.java
  src/main/java/ru/investbook/web/forms/service/SecurityDescriptionFormsService.java
  src/main/java/ru/investbook/web/forms/service/SecurityEventCashFlowFormsService.java
  src/main/java/ru/investbook/web/forms/service/SecurityQuoteFormsService.java
  src/main/java/ru/investbook/web/forms/service/SecurityRepositoryHelper.java
  src/main/java/ru/investbook/web/forms/service/TransactionFormsService.java
  src/main/resources/templates/security-descriptions/edit-form.html
  src/main/resources/templates/security-descriptions/table.html
  src/main/resources/templates/security-descriptions/view-single.html
  src/main/resources/templates/security-quotes/edit-form.html
  src/main/resources/templates/security-quotes/table.html
  src/main/resources/templates/transactions/edit-form.html
Labels: major, task

#383 Поправить стилистику, орфографию и грамматику документации
  docs/dbms-changing.md
  docs/extension-developer-guide.md
  docs/install-on-linux.md
  docs/install-on-windows-by-zip.md
  docs/install-on-windows.md
  src/test/java/ru/investbook/InvestbookApplicationTest.java
  src/test/java/ru/portfolio/portfolio/PortfolioApplicationTests.java
Labels: major, task

#388 Исправить запуск start.sh для MacOS
  .gitattributes
  src/main/assembly/zip/start.bat
  src/main/assembly/zip/start.sh
Labels: bug, critical

#391 Формы. Не проставляется комментарий по умолчанию для ИИС вычета типа А
  src/main/resources/templates/events/edit-form.html
Labels: bug, minor

#393 Формы. Исправить отображение ЦБ парсера Сербанк Онлайн
  src/main/java/ru/investbook/parser/sber/SecurityHelper.java
  src/main/java/ru/investbook/web/forms/model/SecurityHelper.java
  src/main/java/ru/investbook/web/forms/service/SecurityRepositoryHelper.java
  src/main/resources/db/migration/all/V2021_11_0_5.sql
  src/main/resources/templates/transactions/edit-form.html
Labels: bug, major

#394 Формы. До выгрузки со Smartlab отображать инструменты фондового рынка с дефолтным сектором экономики
  src/main/java/ru/investbook/parser/sber/SecurityHelper.java
  src/main/java/ru/investbook/repository/SecurityRepository.java
  src/main/java/ru/investbook/service/SecuritySectorService.java
  src/main/java/ru/investbook/web/forms/controller/SecurityDescriptionController.java
  src/main/resources/templates/security-descriptions/table.html
Labels: minor, improvement

#396 ВТБ. Исправить парсер списания и зачисления ЦБ
  src/main/java/ru/investbook/parser/vtb/VtbSecurityDepositAndWithdrawalTable.java
  src/main/java/ru/investbook/report/excel/StockMarketProfitExcelTableFactory.java
  src/main/resources/templates/security-deposit/edit-form.html
Labels: bug, major

#397 Не отображается сделка по срочному контракту, если она одна
  src/main/java/ru/investbook/report/DerivativeEventsFactory.java
  src/main/java/ru/investbook/report/excel/DerivativesMarketProfitExcelTableFactory.java
Labels: bug, major
