Repository spacious-team/investbook, pull requests merged in 2022-04, with the labels that each got.

#455 Исправления документации для запуска в docker
  docs/install-on-linux.md
  docs/run-by-docker.md
  pom.xml
  src/main/resources/application-h2.properties
  src/main/resources/templates/index.html
Labels: major, task

#457 Формы. Разрешить не указывать ISIN
  src/main/java/ru/investbook/entity/SecurityEntity.java
  src/main/java/ru/investbook/openformat/OpenFormatHelper.java
  src/main/java/ru/investbook/parser/sber/SecurityHelper.java
  src/main/java/ru/investbook/parser/uralsib/SecurityRegistryHelper.java
  src/main/java/ru/investbook/web/forms/model/SecurityDescriptionModel.java
  src/main/java/ru/investbook/web/forms/model/SecurityHelper.java
  src/main/java/ru/investbook/web/forms/model/SplitModel.java
  src/main/java/ru/investbook/web/forms/service/SecurityRepositoryHelper.java
  src/main/java/ru/investbook/web/forms/service/TransactionFormsService.java
  src/main/resources/templates/events/edit-form.html
  src/main/resources/templates/security-deposit/create-split-form.html
  src/main/resources/templates/security-deposit/edit-form.html
  src/main/resources/templates/security-descriptions/edit-form.html
  src/main/resources/templates/security-events/edit-form.html
  src/main/resources/templates/security-quotes/edit-form.html
  src/main/resources/templates/transactions/edit-form.html
Labels: major, improvement

#458 Релиз 2022.5
  .github/workflows/publish-docker.yml
  README.md
  docs/developer-guide.md
  docs/documentation.md
  docs/install-on-linux.md
  docs/run-by-docker.md
  pom.xml
  src/main/java/ru/investbook/entity/SecurityEntity.java
  src/main/java/ru/investbook/openformat/OpenFormatHelper.java
  src/main/java/ru/investbook/openformat/v1_1_0/AssetPof.java
  src/main/java/ru/investbook/openformat/v1_1_0/PaymentPof.java
  src/main/java/ru/investbook/openformat/v1_1_0/PortfolioOpenFormatPersister.java
  src/main/java/ru/investbook/openformat/v1_1_0/TradePof.java
  src/main/java/ru/investbook/openformat/v1_1_0/TransferPof.java
  src/main/java/ru/investbook/parser/SecurityRegistrar.java
  src/main/java/ru/investbook/parser/SecurityRegistrarImpl.java
  src/main/java/ru/investbook/parser/sber/SecurityHelper.java
  src/main/java/ru/investbook/parser/uralsib/SecurityRegistryHelper.java
  src/main/java/ru/investbook/web/forms/controller/EventCashFlowController.java
  src/main/java/ru/investbook/web/forms/model/EventCashFlowModel.java
  src/main/java/ru/investbook/web/forms/model/SecurityDescriptionModel.java
  src/main/java/ru/investbook/web/forms/model/SecurityEventCashFlowModel.java
  src/main/java/ru/investbook/web/forms/model/SecurityHelper.java
  src/main/java/ru/investbook/web/forms/model/SplitModel.java
  src/main/java/ru/investbook/web/forms/service/EventCashFlowFormsService.java
  src/main/java/ru/investbook/web/forms/service/SecurityRepositoryHelper.java
  src/main/java/ru/investbook/web/forms/service/TransactionFormsService.java
  src/main/resources/application-h2.properties
  src/main/resources/static/portfolio-open-format/index.html
  src/main/resources/templates/events/edit-form.html
  src/main/resources/templates/events/view-single.html
  src/main/resources/templates/index.html
  src/main/resources/templates/security-deposit/create-split-form.html
  src/main/resources/templates/security-deposit/edit-form.html
  src/main/resources/templates/security-descriptions/edit-form.html
  src/main/resources/templates/security-events/edit-form.html
  src/main/resources/templates/security-events/view-single.html
  src/main/resources/templates/security-quotes/edit-form.html
  src/main/resources/templates/transactions/edit-form.html
Labels: major, task

#460 Исправить восстановление из бэкапа котировок и секторов экономики
  src/main/java/ru/investbook/openformat/v1_1_0/PortfolioOpenFormatPersister.java
Labels: bug, major

#462 ВТБ. Парсер вариационной маржи
  src/main/asciidoc/vtb.adoc
  src/main/java/ru/investbook/parser/vtb/AbstractVtbCashFlowTable.java
  src/main/java/ru/investbook/parser/vtb/CashFlowEventTable.java
  src/main/java/ru/investbook/parser/vtb/VtbDerivativeCashFlowTable.java
  src/main/java/ru/investbook/parser/vtb/VtbForeignExchangeTransactionTable.java
  src/main/java/ru/investbook/parser/vtb/VtbReportTables.java
  src/main/java/ru/investbook/web/forms/controller/PortfolioController.java
Labels: feature, major

#463 Тинькофф. Сплит акций
  docs/run-by-docker.md
  src/main/asciidoc/index.adoc
  src/main/java/ru/investbook/parser/tinkoff/TinkoffDepositAndWithdrawalTable.java
  src/main/java/ru/investbook/parser/tinkoff/TinkoffReportTables.java
  src/main/resources/templates/broker-file-reports.html
Labels: feature, major

#464 Релиз 2022.6
  README.md
  docs/developer-guide.md
  docs/run-by-docker.md
  pom.xml
  src/main/asciidoc/3-ndfl.adoc
  src/main/asciidoc/cash-flow.adoc
  src/main/asciidoc/commission.adoc
  src/main/asciidoc/derivatives-market-profit.adoc
  src/main/asciidoc/derivatives-market-total-profit.adoc
  src/main/asciidoc/foreign-market-profit.adoc
  src/main/asciidoc/foreign-portfolio-payment.adoc
  src/main/asciidoc/iis-tax.adoc
  src/main/asciidoc/index.adoc
  src/main/asciidoc/portfolio-analysis.adoc
  src/main/asciidoc/portfolio-status.adoc
  src/main/asciidoc/psb.adoc
  src/main/asciidoc/sber.adoc
  src/main/asciidoc/stock-market-profit.adoc
  src/main/asciidoc/tax.adoc
  src/main/asciidoc/vtb.adoc
  src/main/java/ru/investbook/openformat/v1_1_0/PortfolioOpenFormatPersister.java
  src/main/java/ru/investbook/parser/tinkoff/TinkoffDepositAndWithdrawalTable.java
  src/main/java/ru/investbook/parser/tinkoff/TinkoffReportTables.java
  src/main/java/ru/investbook/parser/vtb/AbstractVtbCashFlowTable.java
  src/main/java/ru/investbook/parser/vtb/CashFlowEventTable.java
  src/main/java/ru/investbook/parser/vtb/VtbDerivativeCashFlowTable.java
  src/main/java/ru/investbook/parser/vtb/VtbForeignExchangeTransactionTable.java
  src/main/java/ru/investbook/parser/vtb/VtbReportTables.java
  src/main/java/ru/investbook/web/forms/controller/PortfolioController.java
  src/main/resources/templates/broker-file-reports.html
Labels: major, task

#467 Update commission.adoc
  src/main/asciidoc/commission.adoc
Labels: doc, minor

#470 Update ForeignExchangeRateRestController.java
  src/main/java/ru/investbook/api/ForeignExchangeRateRestController.java
Labels: doc, minor

#471 Сборка отчета в html формате
  docs/run-by-docker.md
  pom.xml
  src/main/asciidoc/portfolio-status.adoc
  src/main/java/ru/investbook/parser/AbstractExcelBrokerReport.java
  src/main/java/ru/investbook/parser/investbook/InvestbookBrokerReport.java
  src/main/java/ru/investbook/report/excel/CashFlowExcelTableView.java
  src/main/java/ru/investbook/report/excel/CellStyles.java
  src/main/java/ru/investbook/report/excel/CommissionExcelTableView.java
  src/main/java/ru/investbook/report/excel/DerivativesMarketProfitExcelTableView.java
  src/main/java/ru/investbook/report/excel/DerivativesMarketTotalProfitExcelTableView.java
  src/main/java/ru/investbook/report/excel/ExcelConditionalFormatHelper.java
  src/main/java/ru/investbook/report/excel/ExcelFormulaHelper.java
  src/main/java/ru/investbook/report/excel/ExcelView.java
  src/main/java/ru/investbook/report/excel/ForeignMarketProfitExcelTableView.java
  src/main/java/ru/investbook/report/excel/PortfolioAnalysisExcelTableView.java
  src/main/java/ru/investbook/report/excel/PortfolioStatusExcelTableFactory.java
  src/main/java/ru/investbook/report/excel/PortfolioStatusExcelTableFactoryProportionHelper.java
  src/main/java/ru/investbook/report/excel/PortfolioStatusExcelTableView.java
  src/main/java/ru/investbook/report/excel/StockMarketProfitExcelTableView.java
  src/main/java/ru/investbook/report/excel/TaxExcelTableView.java
  src/main/java/ru/investbook/report/html/ExcelFormulaEvaluatorHelper.java
  src/main/java/ru/investbook/report/html/HtmlCellStyles.java
  src/main/java/ru/investbook/report/html/HtmlView.java
  src/main/java/ru/investbook/web/InvestbookReportController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/select-period.html
Labels: feature, major

#456 Обновить java до 18
  README.md
  docs/developer-guide.md
  docs/install-on-linux.md
  docs/install-on-windows-by-zip.md
  pom.xml
  src/main/assembly/zip/start.bat
  src/main/assembly/zip/start.sh
Labels: major, task, limitation

#477 Улучшить читаемость html отчета
  src/main/asciidoc/index.adoc
  src/main/asciidoc/investbook-report.adoc
  src/main/java/ru/investbook/report/excel/DerivativesMarketTotalProfitExcelTableView.java
  src/main/java/ru/investbook/report/excel/PortfolioAnalysisExcelTableView.java
  src/main/java/ru/investbook/report/excel/PortfolioStatusExcelTableView.java
  src/main/java/ru/investbook/report/html/HtmlView.java
  src/main/resources/templates/select-period.html
Labels: minor, improvement

#474 Релиз 2022.7
  .mvn/wrapper/maven-wrapper.properties
  README.md
  docs/developer-guide.md
  docs/install-on-linux.md
  docs/install-on-windows-by-zip.md
  docs/run-by-docker.md
  pom.xml
  src/main/asciidoc/commission.adoc
  src/main/asciidoc/index.adoc
  src/main/asciidoc/investbook-report.adoc
  src/main/asciidoc/portfolio-status.adoc
  src/main/assembly/zip/start.bat
  src/main/assembly/zip/start.sh
  src/main/java/ru/investbook/api/ForeignExchangeRateRestController.java
  src/main/java/ru/investbook/parser/AbstractExcelBrokerReport.java
  src/main/java/ru/investbook/parser/investbook/InvestbookBrokerReport.java
  src/main/java/ru/investbook/report/excel/CashFlowExcelTableView.java
  src/main/java/ru/investbook/report/excel/CellStyles.java
  src/main/java/ru/investbook/report/excel/CommissionExcelTableView.java
  src/main/java/ru/investbook/report/excel/DerivativesMarketProfitExcelTableView.java
  src/main/java/ru/investbook/report/excel/DerivativesMarketTotalProfitExcelTableView.java
  src/main/java/ru/investbook/report/excel/ExcelConditionalFormatHelper.java
  src/main/java/ru/investbook/report/excel/ExcelFormulaHelper.java
  src/main/java/ru/investbook/report/excel/ExcelView.java
  src/main/java/ru/investbook/report/excel/ForeignMarketProfitExcelTableView.java
  src/main/java/ru/investbook/report/excel/PortfolioAnalysisExcelTableView.java
  src/main/java/ru/investbook/report/excel/PortfolioStatusExcelTableFactory.java
  src/main/java/ru/investbook/report/excel/PortfolioStatusExcelTableFactoryProportionHelper.java
  src/main/java/ru/investbook/report/excel/PortfolioStatusExcelTableView.java
  src/main/java/ru/investbook/report/excel/StockMarketProfitExcelTableView.java
  src/main/java/ru/investbook/report/excel/TaxExcelTableView.java
  src/main/java/ru/investbook/report/html/ExcelFormulaEvaluatorHelper.java
  src/main/java/ru/investbook/report/html/HtmlCellStyles.java
  src/main/java/ru/investbook/report/html/HtmlView.java
  src/main/java/ru/investbook/web/InvestbookReportController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/select-period.html
Labels: major, task
