Repository spacious-team/investbook, pull requests merged in 2022-02, with the labels that each got.

#418 fix ВТБ - не распознаются купоны
  src/main/java/ru/investbook/parser/vtb/VtbSecuritiesTable.java
  src/main/java/ru/investbook/parser/vtb/VtbSecurityFlowTable.java
Labels: bug, major

#417 Сохранение и чтение данных Portfolio Open Format
  src/main/asciidoc/index.adoc
  src/main/asciidoc/investbook-forms.adoc
  src/main/asciidoc/investbook-input-format.adoc
  src/main/java/ru/investbook/openformat/PortfolioOpenFormatRestController.java
  src/main/java/ru/investbook/openformat/v1_1_0/AccountPof.java
  src/main/java/ru/investbook/openformat/v1_1_0/AccountTypePof.java
  src/main/java/ru/investbook/openformat/v1_1_0/AssetPof.java
  src/main/java/ru/investbook/openformat/v1_1_0/CashBalancesPof.java
  src/main/java/ru/investbook/openformat/v1_1_0/CashFlowPof.java
  src/main/java/ru/investbook/openformat/v1_1_0/PaymentPof.java
  src/main/java/ru/investbook/openformat/v1_1_0/PaymentTypePof.java
  src/main/java/ru/investbook/openformat/v1_1_0/PortfolioOpenFormatBuilder.java
  src/main/java/ru/investbook/openformat/v1_1_0/PortfolioOpenFormatPersister.java
  src/main/java/ru/investbook/openformat/v1_1_0/PortfolioOpenFormatV1_1_0.java
  src/main/java/ru/investbook/openformat/v1_1_0/SecurityTypeHelper.java
  src/main/java/ru/investbook/openformat/v1_1_0/TradePof.java
  src/main/java/ru/investbook/openformat/v1_1_0/TransferPof.java
  src/main/java/ru/investbook/openformat/v1_1_0/VndInvestbookPof.java
  src/main/java/ru/investbook/parser/InvestbookApiClient.java
  src/main/java/ru/investbook/parser/ValidatorService.java
  src/main/java/ru/investbook/repository/EventCashFlowRepository.java
  src/main/java/ru/investbook/repository/PortfolioCashRepository.java
  src/main/java/ru/investbook/repository/PortfolioPropertyRepository.java
  src/main/java/ru/investbook/repository/SecurityEventCashFlowRepository.java
  src/main/java/ru/investbook/repository/TransactionRepository.java
  src/main/java/ru/investbook/service/AssetsAndCashServiceImpl.java
  src/main/java/ru/investbook/web/HttpAttachResponseHelper.java
  src/main/java/ru/investbook/web/InvestbookReportController.java
  src/main/java/ru/investbook/web/ReportControllerHelper.java
  src/main/java/ru/investbook/web/forms/controller/PortfolioController.java
  src/main/resources/static/forms.html
  src/main/resources/static/portfolio-open-format/index.html
  src/main/resources/templates/success.html
Labels: feature, major

#421 Учитывать сплит акций при расчете средней цены покупки
  src/main/java/ru/investbook/repository/TransactionCashFlowRepository.java
  src/main/java/ru/investbook/repository/TransactionRepository.java
  src/main/java/ru/investbook/service/SecurityProfitServiceImpl.java
Labels: bug, major

#423 Сбербанк Онлайн. Исправить парсер знака комиссии сделки
  src/main/java/ru/investbook/parser/sber/transaction/SberTrSecurityTransactionTable.java
Labels: bug, critical

#424 Дорботка экспорта и импорта в формате Portfolio Open Format
  src/main/java/ru/investbook/openformat/OpenFormatHelper.java
  src/main/java/ru/investbook/openformat/PortfolioOpenFormatRestController.java
  src/main/java/ru/investbook/openformat/v1_1_0/AccountPof.java
  src/main/java/ru/investbook/openformat/v1_1_0/CashBalancesPof.java
  src/main/java/ru/investbook/openformat/v1_1_0/CashFlowPof.java
  src/main/java/ru/investbook/openformat/v1_1_0/PaymentPof.java
  src/main/java/ru/investbook/openformat/v1_1_0/PortfolioOpenFormatPersister.java
  src/main/java/ru/investbook/openformat/v1_1_0/TradePof.java
  src/main/java/ru/investbook/report/ForeignExchangeRateService.java
  src/main/resources/static/forms.html
  src/main/resources/static/portfolio-open-format/index.html
  src/main/resources/templates/index.html
  src/main/resources/templates/portfolio-properties/table.html
  src/main/resources/templates/portfolio-properties/total-assets-edit-form.html
  src/main/resources/templates/portfolio-properties/total-assets-view-single.html
Labels: major, task

#427 Повысить точность расчета "Курсового дохода" в таблице "Портфель"
  src/main/java/ru/investbook/service/SecurityProfitServiceImpl.java
Labels: major, improvement

#431 Добавить поддержку новых срочных контракты Мосбиржи
  src/main/java/ru/investbook/service/moex/MoexDerivativeCodeService.java
Labels: major, improvement

#433 Обновить Table Wrapper API
  pom.xml
  src/main/java/ru/investbook/parser/psb/ForeignExchangeRateTable.java
  src/main/java/ru/investbook/parser/psb/PortfolioPropertyTable.java
  src/main/java/ru/investbook/parser/psb/PsbBrokerReport.java
  src/main/java/ru/investbook/parser/psb/foreignmarket/ForeignExchangeCashTable.java
  src/main/java/ru/investbook/parser/psb/foreignmarket/ForeignExchangePortfolioPropertyTable.java
  src/main/java/ru/investbook/parser/uralsib/ForeignExchangeRateTable.java
  src/main/java/ru/investbook/parser/uralsib/UralsibBrokerReport.java
  src/main/java/ru/investbook/parser/vtb/VtbBrokerReport.java
Labels: minor, task

#435 Регистрация ценных бумаг по тикеру
  src/main/java/ru/investbook/parser/SecurityRegistrar.java
  src/main/java/ru/investbook/parser/SecurityRegistrarImpl.java
  src/main/java/ru/investbook/parser/psb/CouponAmortizationRedemptionTable.java
  src/main/java/ru/investbook/parser/psb/DividendTable.java
  src/main/java/ru/investbook/parser/psb/SecuritiesTable.java
  src/main/java/ru/investbook/parser/psb/SecurityQuoteTable.java
  src/main/java/ru/investbook/parser/psb/SecurityTransactionTable.java
  src/main/java/ru/investbook/parser/sber/SecurityHelper.java
  src/main/java/ru/investbook/parser/uralsib/SecuritiesTable.java
  src/main/java/ru/investbook/parser/uralsib/SecurityQuoteTable.java
  src/main/java/ru/investbook/parser/uralsib/SecurityTransactionTable.java
  src/main/java/ru/investbook/parser/vtb/VtbCouponAmortizationRedemptionTable.java
  src/main/java/ru/investbook/parser/vtb/VtbSecuritiesTable.java
  src/main/java/ru/investbook/parser/vtb/VtbSecurityDepositAndWithdrawalTable.java
  src/main/java/ru/investbook/parser/vtb/VtbSecurityFlowTable.java
  src/main/java/ru/investbook/parser/vtb/VtbSecurityQuoteTable.java
  src/main/java/ru/investbook/parser/vtb/VtbSecurityTransactionTable.java
Labels: feature, major

#436 Уралсиб. В отчете встречаются невалидные ISIN
  pom.xml
  src/main/java/ru/investbook/parser/SecurityRegistrarImpl.java
  src/main/java/ru/investbook/parser/uralsib/SecuritiesTable.java
  src/main/java/ru/investbook/parser/uralsib/SecurityQuoteTable.java
  src/main/java/ru/investbook/parser/uralsib/SecurityRegistryHelper.java
  src/main/java/ru/investbook/parser/uralsib/SecurityTransactionTable.java
Labels: bug, critical

#437 Уралсиб. Исправить ошибку сохранения вариационной маржи
  src/main/java/ru/investbook/parser/InvestbookApiClient.java
Labels: bug, critical
