Repository spacious-team/investbook, pull requests merged in 2024-11, with the labels that each got.

#614 Add page loading animation before spring init
  src/main/java/ru/investbook/ApplicationFailedRunListener.java
  src/main/java/ru/investbook/BrowserHomePageOpener.java
  src/main/java/ru/investbook/InvestbookApplication.java
  src/main/java/ru/investbook/WebConfig.java
  src/main/java/ru/investbook/loadingpage/LoadingPageServer.java
  src/main/java/ru/investbook/loadingpage/LoadingPageServerUtils.java
  src/main/resources/templates/loading.html
  src/test/java/ru/investbook/LoadingPageServerTests.java
Labels: major, task

#612 Обновить Java до 23 версии
  .github/workflows/publish-docker.yml
  .github/workflows/unit-tests.yml
  README-en.md
  README.md
  codecov.yml
  docs/install-on-linux.md
  docs/install-on-windows-by-zip.md
  docs/install-on-windows.md
  docs/run-by-docker.md
  pom.xml
  src/main/assembly/zip/start.bat
  src/main/assembly/zip/start.sh
  src/main/java/ru/investbook/service/cbr/CbrForeignExchangeRateServiceXmlImpl.java
Labels: major, task

#618 Не запрашивать пароль администратора при установке
  docs/developer-guide.md
  pom.xml
  src/main/assembly/jpackage/dir.xml
  src/main/assembly/zip/zip.xml
  src/main/java/ru/investbook/ApplicationFailedRunListener.java
  src/main/java/ru/investbook/loadingpage/LoadingPageServerUtils.java
Labels: minor, task

#623 Не открывать браузер в режиме debug
  src/main/java/ru/investbook/InvestbookApplication.java
  src/main/java/ru/investbook/loadingpage/LoadingPageServerUtils.java
  src/main/resources/application-dev.properties
Labels: minor, task

#624 Добавить фильтр по типу операции
  src/main/java/ru/investbook/repository/specs/EventCashFlowEntitySearchSpecification.java
  src/main/java/ru/investbook/repository/specs/ForeignExchangeRateSearchSpecification.java
  src/main/java/ru/investbook/repository/specs/PortfolioCashSearchSpecification.java
  src/main/java/ru/investbook/repository/specs/PortfolioPropertySearchSpecification.java
  src/main/java/ru/investbook/repository/specs/SecurityDepositSearchSpecification.java
  src/main/java/ru/investbook/repository/specs/SecurityDescriptionSearchSpecification.java
  src/main/java/ru/investbook/repository/specs/SecurityEventCashFlowEntitySearchSpecification.java
  src/main/java/ru/investbook/repository/specs/SecurityQuoteSearchSpecification.java
  src/main/java/ru/investbook/repository/specs/SpecificationHelper.java
  src/main/java/ru/investbook/repository/specs/TransactionSearchSpecification.java
  src/main/java/ru/investbook/web/forms/model/EventCashFlowModel.java
  src/main/java/ru/investbook/web/forms/model/filter/EventCashFlowFormFilterModel.java
  src/main/java/ru/investbook/web/forms/model/filter/ForeignExchangeRateFormFilterModel.java
  src/main/java/ru/investbook/web/forms/model/filter/PortfolioCashFormFilterModel.java
  src/main/java/ru/investbook/web/forms/model/filter/PortfolioPropertyFormFilterModel.java
  src/main/java/ru/investbook/web/forms/model/filter/SecurityDescriptionFormFilterModel.java
  src/main/java/ru/investbook/web/forms/model/filter/SecurityEventCashFlowFormFilterModel.java
  src/main/java/ru/investbook/web/forms/model/filter/SecurityQuoteFormFilterModel.java
  src/main/java/ru/investbook/web/forms/model/filter/TransactionFormFilterModel.java
  src/main/java/ru/investbook/web/forms/service/EventCashFlowFormsService.java
  src/main/java/ru/investbook/web/forms/service/SecurityEventCashFlowFormsService.java
  src/main/java/ru/investbook/web/forms/service/SecurityRepositoryHelper.java
  src/main/resources/templates/events/edit-form.html
  src/main/resources/templates/events/table.html
  src/main/resources/templates/events/view-single.html
  src/main/resources/templates/fragments/search.html
  src/main/resources/templates/security-events/edit-form.html
  src/main/resources/templates/security-events/table.html
Labels: feature, major

#625 Отображать события по дивидендам, купонам и другим начислениям, где не указана ценная бумага
  src/main/resources/templates/events/table.html
Labels: feature, major
